---
- hosts: clients
  tasks:
  - name: upgrading packages on the system
    apt: upgrade=dist
  - name: installing additional packages
    apt: name={{item}} update_cache=yes
    with_items:
      - atop
      - cpufrequtils
      - git
      - htop
      - libffi-dev
      - libssl-dev
      - linux-tools-generic
      - openjdk-8-jdk
      - python-pip
      - python-virtualenv
      - sshpass
      - rpm2cpio
  - name: adding Couchbase repository
    apt: deb=http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb
  - name: installing libcouchbase
    apt: name={{item}} update_cache=yes
    with_items:
    - build-essential
    - libcouchbase-dev
    - libcouchbase2-bin
  - name: disabling scheduled fstrim jobs
    file: path=/etc/cron.weekly/fstrim state=absent
