---
- hosts: kv:index:n1ql
  tasks:
  - name: upgrading packages on the system
    yum: state=latest name=epel-release
  - name: installing additional packages
    yum: state=latest name={{item}}
    with_items:
      - atop
      - fio
      - gdb
      - hdparm
      - htop
      - iotop
      - iperf
      - iptraf
      - lsof
      - moreutils
      - net-tools
      - numactl
      - psmisc
      - rsync
      - sysstat
      - tree
      - vim
      - wget

- hosts: kv:index:n1ql
  tasks:
  - name: flushing iptables rules
    shell: iptables -F

- hosts: kv:index:n1ql
  tasks:
  - name: creating new "couchbase" group
    group: name=couchbase
  - name: creating new "couchbase" user
    user: name=couchbase group=couchbase

- hosts: kv:index:n1ql
  tasks:
  - name: creating the "/data" directory
    file: path=/data  owner=couchbase group=couchbase

- hosts: kv
  tasks:
  - stat: path=/index
    register: index
  - name: creating the "/index" directory
    file: path=/index owner=couchbase group=couchbase
    when: index.stat.exists
