---
- hosts: influxdb_servers:local
  tasks:
  - name: Install influxdb
    apt: deb=https://dl.influxdata.com/influxdb/releases/influxdb_1.0.0-beta3_amd64.deb
  - name: Start the InfluxDB service
    service: name=influxdb state=started enabled=yes

