---
- hosts: kv:index:n1ql
  tasks:
  - name: downloading the specifed package
    get_url: url={{ url }} dest=/tmp
    register: package
  - name: installing the specifed package
    yum: name={{ package.dest }} state=present
