---
- hosts: kv:index:n1ql
  tasks:
  - name: killing the processes
    shell: 'killall -I -g -q -s SIGKILL {{item}} || true'
    with_items:
     - epmd
     - beam.smp
     - cbq-engine
     - cbft
     - couch_view_index_updater
     - goport
     - goxdcr
     - indexer
     - memcached
     - moxi
  - name: uninstalling the Couchbase Server package
    yum: name=couchbase-server state=absent
  - name: remove Couchbase Server files
    file: path=/opt/couchbase state=absent

- hosts: kv:index:n1ql
  tasks:
  - name: Removing the files remaining in the "/data" directory
    shell: rm -fr /data/*

- hosts: kv
  tasks:
  - stat: path=/index
    register: index
  - name: removing files in remaining the "/index" directory
    shell: rm -fr /index/*
    when: index.stat.exists
